{
 "title": "tBTC Node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "chain_address",
    "query": "0x34694655353DAD30E188236E205c1a7D707e9A40,0x3cA4486c60D10aBFeD5850dAA7820D8f5F06407a"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum by (chain_address) (up{chain_address=\"$chain_address\"}) OR clamp_max(absent(up{chain_address=\"$chain_address\"}),0))",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Pre Params Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tbtc_pre_params_count{chain_address=\"$chain_address\"}",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Uptime (last 30 days)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(up{chain_address=\"$chain_address\"}[2592000s:60s]) / 43200 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH connectivity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_connectivity{chain_address=\"$chain_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC connectivity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "btc_connectivity{chain_address=\"$chain_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (last 14 days)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(up{chain_address=\"$chain_address\"}[1209600s:60s]) / 20160 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_info{chain_address=\"$chain_address\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime (last 7 days)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(up{chain_address=\"$chain_address\"}[604800s:60s]) / 10080 * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum by (chain_address) (up{chain_address=\"$chain_address\"}) OR clamp_max(absent(up{chain_address=\"$chain_address\"}),0))",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Connected Peers Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "connected_peers_count{chain_address=\"$chain_address\"}",
     "legendFormat": "{{chain_address}}"
    }
   ]
  },
  {
   "title": "Connected Bootstrap Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "connected_bootstrap_count{chain_address=\"$chain_address\"}",
     "legendFormat": "{{chain_address}}"
    }
   ]
  }
 ]
}